version: '3.8'
services:
  app:
    image: 0xc000007bl/rdpctd
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./apps/site/nginx.conf:/etc/nginx/nginx.conf
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www.(.*)'
      - 'traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}'
      - 'traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true'

      - 'traefik.http.routers.site.rule=Host(`${HOST}`) || Host(`www.${HOST}`)'
      - 'traefik.http.routers.site.entrypoints=websecure'
      - 'traefik.http.routers.site.tls.certresolver=myresolver'
      - 'traefik.http.routers.site}.middlewares=redirect-to-non-www'
      - 'traefik.http.services.site.loadbalancer.server.port=80'

      - 'traefik.docker.network=site_default'

