name: lint

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

permissions:
  actions: read
  contents: read

jobs:
  lint:
    name: Linting project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --silent --ignore-scripts

      - name: Lint project (typescript)
        run: npx nx run site:lint
